
export const TILE_ORIGINAL_WIDTH = 590;
export const TILE_ORIGINAL_HEIGHT = 371;

export const TILE_DISPLAY_WIDTH = 256;

export const ASPECT_RATIO = TILE_ORIGINAL_HEIGHT / TILE_ORIGINAL_WIDTH;
export const TILE_DISPLAY_HEIGHT = TILE_DISPLAY_WIDTH * ASPECT_RATIO;

export const UNIT_IMAGE = process.env.PUBLIC_URL + '/units/unit.png';